CREATE TABLE "DatePlace" (
  "id" SERIAL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "lat" DOUBLE PRECISION NOT NULL,
  "lng" DOUBLE PRECISION NOT NULL,
  "memo" TEXT NOT NULL DEFAULT '',
  "visitedAt" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
